import type { Language } from "@/lib/i18n";

export function getApplicationCopy(lang: Language) {
  return lang === "en"
    ? {
        title: "Your application",
        subtitle: "Share your details so we can get in touch.",
        jobLabel: "Position",
        formError: "Please fix the highlighted fields and try again.",
        success: "Thank you! Your application has been submitted for review.",
        labels: {
          firstName: "First name",
          lastName: "Last name",
          email: "Email",
          phone: "Phone",
          location: "Location",
          experience: "Years of experience",
          cv: "Upload CV",
        },
        placeholders: {
          firstName: "John",
          lastName: "Doe",
          email: "name@company.com",
          phone: "+1 (555) 123-4567",
          location: "City, Country",
        },
        experienceOptions: [
          { value: "", label: "Select..." },
          { value: "0-2", label: "0-2 years" },
          { value: "2-5", label: "2-5 years" },
          { value: "5-10", label: "5-10 years" },
          { value: "10+", label: "10+ years" },
        ],
        required: "Required",
        fileHint: "PDF or DOC. Maximum file size: 5 MB.",
        submit: "Submit application",
        errors: {
          firstNameRequired: "First name is required.",
          firstNameLength: "First name should be at least 2 characters.",
          lastNameRequired: "Last name is required.",
          lastNameLength: "Last name should be at least 2 characters.",
          emailRequired: "Email is required.",
          emailInvalid: "Please enter a valid email address.",
          phoneRequired: "Phone number is required.",
          phoneInvalid: "Please enter a valid phone number.",
          locationInvalid: "Location should be at least 2 characters.",
          experienceRequired: "Please select your experience level.",
          cvRequired: "Please upload your CV.",
          cvType: "File must be PDF or Word format.",
          cvSize: "File size must be 5 MB or less.",
        },
      }
    : {
        title: "فرم درخواست همکاری",
        subtitle:
          "اطلاعات خود را وارد کنید تا بتوانیم با شما در ارتباط باشیم.",
        jobLabel: "موقعیت همکاری",
        formError: "لطفاً فیلدهای مشخص‌شده را اصلاح کنید و دوباره تلاش کنید.",
        success: "سپاسگزاریم. درخواست شما برای بررسی دریافت شد.",
        labels: {
          firstName: "نام",
          lastName: "نام خانوادگی",
          email: "ایمیل",
          phone: "شماره تماس",
          location: "شهر / کشور",
          experience: "سابقه کاری",
          cv: "بارگذاری رزومه",
        },
        placeholders: {
          firstName: "علی",
          lastName: "علی‌پور",
          email: "name@company.com",
          phone: "+98 912 000 0000",
          location: "شهر، کشور",
        },
        experienceOptions: [
          { value: "", label: "انتخاب کنید..." },
          { value: "0-2", label: "۰ تا ۲ سال" },
          { value: "2-5", label: "۲ تا ۵ سال" },
          { value: "5-10", label: "۵ تا ۱۰ سال" },
          { value: "10+", label: "بیش از ۱۰ سال" },
        ],
        required: "ضروری",
        fileHint: "فرمت PDF یا DOC. حداکثر حجم فایل: ۵ مگابایت.",
        submit: "ارسال درخواست همکاری",
        errors: {
          firstNameRequired: "وارد کردن نام ضروری است.",
          firstNameLength: "نام باید حداقل ۲ حرف باشد.",
          lastNameRequired: "وارد کردن نام خانوادگی ضروری است.",
          lastNameLength: "نام خانوادگی باید حداقل ۲ حرف باشد.",
          emailRequired: "وارد کردن ایمیل ضروری است.",
          emailInvalid: "لطفاً یک ایمیل معتبر وارد کنید.",
          phoneRequired: "وارد کردن شماره تماس ضروری است.",
          phoneInvalid: "لطفاً یک شماره تماس معتبر وارد کنید.",
          locationInvalid: "موقعیت مکانی باید حداقل ۲ حرف باشد.",
          experienceRequired: "لطفاً سابقه کاری خود را انتخاب کنید.",
          cvRequired: "لطفاً رزومه خود را بارگذاری کنید.",
          cvType: "فرمت فایل باید PDF یا Word باشد.",
          cvSize: "حجم فایل باید حداکثر ۵ مگابایت باشد.",
        },
      };
}
