export interface Product {
  id: number;
  nameEn: string;
  nameFa: string;
  category: "rice" | "legumes" | "seeds" | "nuts" | "spices" | "sugar";
  originEn: string;
  originFa: string;
  gradeEn: string;
  gradeFa: string;
  descriptionEn: string;
  descriptionFa: string;
  packagingOptionsEn: string[];
  packagingOptionsFa: string[];
  certifications: string[];
  shelfLifeEn: string;
  shelfLifeFa: string;
  minOrderEn: string;
  minOrderFa: string;
  image: string;
  images: string[];
  priceRangeEn: string;
  priceRangeFa: string;
  available: boolean;
}

const sharedCertifications = ["ISO 22000", "Quality Checked", "Import Docs"];
const gallery = ["/featured1.jpg", "/featured2.jpg", "/featured3.jpg", "/featured4.jpg"];

export const products: Product[] = [
  {
    id: 1,
    nameEn: "Indian Rice",
    nameFa: "برنج هندی",
    category: "rice",
    originEn: "India",
    originFa: "هند",
    gradeEn: "Premium",
    gradeFa: "ممتاز",
    descriptionEn:
      "Carefully selected Indian rice for dependable supply, consistent cooking quality, and broad foodservice use.",
    descriptionFa:
      "برنج هندی با انتخاب دقیق برای تامین پایدار، کیفیت پخت یکنواخت و مصرف گسترده در بازار غذا.",
    packagingOptionsEn: ["10kg bags", "25kg bags", "50kg bags"],
    packagingOptionsFa: ["کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی", "کیسه ۵۰ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "Up to 24 months in dry storage",
    shelfLifeFa: "تا ۲۴ ماه در انبار خشک",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured1.jpg",
    images: gallery,
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 2,
    nameEn: "Pakistani Rice",
    nameFa: "برنج پاکستانی",
    category: "rice",
    originEn: "Pakistan",
    originFa: "پاکستان",
    gradeEn: "Premium",
    gradeFa: "ممتاز",
    descriptionEn:
      "Aromatic Pakistani rice sourced for steady B2B distribution and reliable batch consistency.",
    descriptionFa:
      "برنج پاکستانی خوش‌عطر برای توزیع B2B منظم و ثبات قابل اتکا در هر محموله.",
    packagingOptionsEn: ["10kg bags", "25kg bags", "50kg bags"],
    packagingOptionsFa: ["کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی", "کیسه ۵۰ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "Up to 24 months in dry storage",
    shelfLifeFa: "تا ۲۴ ماه در انبار خشک",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured2.jpg",
    images: ["/featured2.jpg", "/featured1.jpg", "/featured3.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 3,
    nameEn: "Pinto Beans",
    nameFa: "لوبیا چیتی",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Cleaned and sorted pinto beans for wholesale, retail packing, and institutional kitchens.",
    descriptionFa:
      "لوبیا چیتی پاک‌سازی و سورت‌شده برای عمده‌فروشی، بسته‌بندی فروشگاهی و آشپزخانه‌های سازمانی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured3.jpg",
    images: ["/featured3.jpg", "/featured1.jpg", "/featured5.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 4,
    nameEn: "Red Kidney Beans",
    nameFa: "لوبیا قرمز",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Color-sorted red kidney beans selected for uniform size, cooking performance, and dependable delivery.",
    descriptionFa:
      "لوبیا قرمز سورت‌شده از نظر رنگ و اندازه برای پخت یکنواخت و تحویل قابل اتکا.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured4.jpg",
    images: ["/featured4.jpg", "/featured3.jpg", "/featured2.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 5,
    nameEn: "Black-Eyed Peas",
    nameFa: "لوبیا چشم‌بلبلی",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "A versatile legume line supplied for retail packs, bulk channels, and foodservice demand.",
    descriptionFa:
      "حبوبات پرکاربرد برای بسته‌بندی فروشگاهی، کانال‌های عمده و نیازهای خدمات غذایی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured5.jpg",
    images: ["/featured5.jpg", "/featured3.jpg", "/featured1.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 6,
    nameEn: "Chickpeas",
    nameFa: "نخود",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Selected chickpeas with dependable sizing for processing, foodservice, and retail distribution.",
    descriptionFa:
      "نخود منتخب با اندازه‌بندی قابل اتکا برای فرآوری، خدمات غذایی و توزیع فروشگاهی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured1.jpg",
    images: ["/featured1.jpg", "/featured3.jpg", "/featured4.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 7,
    nameEn: "Black Chickpeas",
    nameFa: "نخود سیاه",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Black chickpeas sourced for specialty demand and stable wholesale availability.",
    descriptionFa:
      "نخود سیاه برای تقاضای تخصصی بازار و تامین پایدار عمده.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured2.jpg",
    images: ["/featured2.jpg", "/featured3.jpg", "/featured5.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 8,
    nameEn: "Green Lentils",
    nameFa: "عدس سبز",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Green lentils selected for clean appearance, stable cooking results, and efficient distribution.",
    descriptionFa:
      "عدس سبز با ظاهر تمیز، نتیجه پخت پایدار و مناسب برای توزیع منظم.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured3.jpg",
    images: ["/featured3.jpg", "/featured1.jpg", "/featured2.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 9,
    nameEn: "Red Lentils",
    nameFa: "عدس قرمز",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Red lentils for fast-cooking applications, foodservice demand, and retail packaging.",
    descriptionFa:
      "عدس قرمز مناسب پخت سریع، نیازهای خدمات غذایی و بسته‌بندی فروشگاهی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured4.jpg",
    images: ["/featured4.jpg", "/featured2.jpg", "/featured3.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 10,
    nameEn: "Mung Beans",
    nameFa: "ماش",
    category: "legumes",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Mung beans supplied for traditional cooking, processing, and consistent wholesale demand.",
    descriptionFa:
      "ماش برای پخت سنتی، فرآوری و تقاضای پایدار عمده‌فروشی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "18-24 months",
    shelfLifeFa: "۱۸ تا ۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured5.jpg",
    images: ["/featured5.jpg", "/featured1.jpg", "/featured4.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 11,
    nameEn: "Popcorn Corn",
    nameFa: "ذرت پاپ‌کورن",
    category: "seeds",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Popcorn corn selected for expansion performance, cleanliness, and foodservice reliability.",
    descriptionFa:
      "ذرت پاپ‌کورن با انتخاب دقیق برای پف‌دهی مناسب، پاکیزگی و کاربری قابل اتکا.",
    packagingOptionsEn: ["10kg bags", "25kg bags", "Bulk supply"],
    packagingOptionsFa: ["کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی", "تامین فله"],
    certifications: sharedCertifications,
    shelfLifeEn: "12-18 months",
    shelfLifeFa: "۱۲ تا ۱۸ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured1.jpg",
    images: ["/featured1.jpg", "/featured5.jpg", "/featured3.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 12,
    nameEn: "Sunflower Seeds",
    nameFa: "تخمه آفتابگردان",
    category: "seeds",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Sunflower seeds sourced for snack, bakery, and wholesale distribution channels.",
    descriptionFa:
      "تخمه آفتابگردان برای بازار تنقلات، نانوایی و کانال‌های توزیع عمده.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured2.jpg",
    images: ["/featured2.jpg", "/featured5.jpg", "/featured4.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 13,
    nameEn: "Sunflower Kernels",
    nameFa: "مغز آفتابگردان",
    category: "seeds",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Ready-to-use sunflower kernels for food manufacturing, bakery, and retail packs.",
    descriptionFa:
      "مغز آفتابگردان آماده مصرف برای صنایع غذایی، نانوایی و بسته‌بندی فروشگاهی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured3.jpg",
    images: ["/featured3.jpg", "/featured2.jpg", "/featured5.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 14,
    nameEn: "Pumpkin Seeds",
    nameFa: "تخمه کدو",
    category: "seeds",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Pumpkin seeds supplied for snack brands, processors, and bulk food buyers.",
    descriptionFa:
      "تخمه کدو برای برندهای تنقلات، واحدهای فرآوری و خریداران عمده مواد غذایی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured4.jpg",
    images: ["/featured4.jpg", "/featured2.jpg", "/featured1.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 15,
    nameEn: "Pumpkin Seed Kernels",
    nameFa: "مغز تخمه کدو",
    category: "seeds",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Shelled pumpkin seed kernels selected for bakery, snack, and ingredient applications.",
    descriptionFa:
      "مغز تخمه کدو برای نانوایی، تنقلات و کاربردهای مواد اولیه غذایی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured5.jpg",
    images: ["/featured5.jpg", "/featured4.jpg", "/featured2.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 16,
    nameEn: "Sesame Seeds",
    nameFa: "کنجد",
    category: "seeds",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Sesame seeds supplied for bakery, confectionery, tahini production, and wholesale channels.",
    descriptionFa:
      "کنجد برای نانوایی، قنادی، تولید ارده و کانال‌های عمده‌فروشی.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "12-18 months",
    shelfLifeFa: "۱۲ تا ۱۸ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured1.jpg",
    images: ["/featured1.jpg", "/featured4.jpg", "/featured3.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 17,
    nameEn: "Walnut",
    nameFa: "گردو",
    category: "nuts",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Premium",
    gradeFa: "ممتاز",
    descriptionEn:
      "Whole walnuts selected for quality appearance, taste, and reliable seasonal availability.",
    descriptionFa:
      "گردوی کامل با انتخاب دقیق از نظر ظاهر، طعم و دسترسی قابل اتکا در فصل تامین.",
    packagingOptionsEn: ["5kg cartons", "10kg cartons", "Bulk supply"],
    packagingOptionsFa: ["کارتن ۵ کیلوگرمی", "کارتن ۱۰ کیلوگرمی", "تامین فله"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured2.jpg",
    images: ["/featured2.jpg", "/featured1.jpg", "/featured5.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 18,
    nameEn: "Walnut Kernels",
    nameFa: "مغز گردو",
    category: "nuts",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Premium",
    gradeFa: "ممتاز",
    descriptionEn:
      "Walnut kernels sorted for confectionery, bakery, foodservice, and retail packing.",
    descriptionFa:
      "مغز گردوی سورت‌شده برای قنادی، نانوایی، خدمات غذایی و بسته‌بندی فروشگاهی.",
    packagingOptionsEn: ["5kg cartons", "10kg cartons", "Bulk supply"],
    packagingOptionsFa: ["کارتن ۵ کیلوگرمی", "کارتن ۱۰ کیلوگرمی", "تامین فله"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured3.jpg",
    images: ["/featured3.jpg", "/featured2.jpg", "/featured5.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 19,
    nameEn: "Cashews",
    nameFa: "بادام هندی",
    category: "nuts",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Premium",
    gradeFa: "ممتاز",
    descriptionEn:
      "Cashews selected for snack brands, retail packing, and ingredient use.",
    descriptionFa:
      "بادام هندی منتخب برای برندهای تنقلات، بسته‌بندی فروشگاهی و مصرف مواد اولیه.",
    packagingOptionsEn: ["5kg cartons", "10kg cartons", "Bulk supply"],
    packagingOptionsFa: ["کارتن ۵ کیلوگرمی", "کارتن ۱۰ کیلوگرمی", "تامین فله"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured4.jpg",
    images: ["/featured4.jpg", "/featured2.jpg", "/featured1.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 20,
    nameEn: "Peanuts",
    nameFa: "بادام زمینی",
    category: "nuts",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Peanuts sourced for roasting, processing, snack production, and bulk distribution.",
    descriptionFa:
      "بادام زمینی برای برشته‌کاری، فرآوری، تولید تنقلات و توزیع عمده.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured5.jpg",
    images: ["/featured5.jpg", "/featured1.jpg", "/featured2.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 21,
    nameEn: "Desiccated Coconut",
    nameFa: "پودر نارگیل",
    category: "nuts",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Desiccated coconut powder for bakery, confectionery, and packaged food manufacturing.",
    descriptionFa:
      "پودر نارگیل برای نانوایی، قنادی و تولید محصولات غذایی بسته‌بندی‌شده.",
    packagingOptionsEn: ["5kg bags", "10kg bags", "25kg bags"],
    packagingOptionsFa: ["کیسه ۵ کیلوگرمی", "کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "12 months",
    shelfLifeFa: "۱۲ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured1.jpg",
    images: ["/featured1.jpg", "/featured5.jpg", "/featured4.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 22,
    nameEn: "Turmeric",
    nameFa: "زردچوبه",
    category: "spices",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Turmeric selected for color, aroma, and dependable supply to seasoning and food producers.",
    descriptionFa:
      "زردچوبه با انتخاب دقیق از نظر رنگ، عطر و تامین قابل اتکا برای تولیدکنندگان ادویه و غذا.",
    packagingOptionsEn: ["1kg packs", "10kg cartons", "25kg bags"],
    packagingOptionsFa: ["بسته ۱ کیلوگرمی", "کارتن ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "24 months",
    shelfLifeFa: "۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured2.jpg",
    images: ["/featured2.jpg", "/featured4.jpg", "/featured1.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 23,
    nameEn: "Black Pepper",
    nameFa: "فلفل سیاه",
    category: "spices",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Black pepper supplied whole or ground for spice blends, food manufacturing, and retail packs.",
    descriptionFa:
      "فلفل سیاه به‌صورت کامل یا آسیاب‌شده برای ترکیب ادویه، تولید غذا و بسته‌بندی فروشگاهی.",
    packagingOptionsEn: ["1kg packs", "10kg cartons", "25kg bags"],
    packagingOptionsFa: ["بسته ۱ کیلوگرمی", "کارتن ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "24 months",
    shelfLifeFa: "۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured3.jpg",
    images: ["/featured3.jpg", "/featured4.jpg", "/featured2.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 24,
    nameEn: "Cardamom",
    nameFa: "هل",
    category: "spices",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Premium",
    gradeFa: "ممتاز",
    descriptionEn:
      "Aromatic cardamom selected for confectionery, beverage, spice, and premium retail uses.",
    descriptionFa:
      "هل معطر برای قنادی، نوشیدنی، ادویه و کاربردهای ممتاز فروشگاهی.",
    packagingOptionsEn: ["500g packs", "5kg cartons", "Bulk supply"],
    packagingOptionsFa: ["بسته ۵۰۰ گرمی", "کارتن ۵ کیلوگرمی", "تامین فله"],
    certifications: sharedCertifications,
    shelfLifeEn: "24 months",
    shelfLifeFa: "۲۴ ماه",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured4.jpg",
    images: ["/featured4.jpg", "/featured3.jpg", "/featured1.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
  {
    id: 25,
    nameEn: "Sugar",
    nameFa: "شکر",
    category: "sugar",
    originEn: "Global supply",
    originFa: "تامین جهانی",
    gradeEn: "Food Grade",
    gradeFa: "گرید غذایی",
    descriptionEn:
      "Essential sugar supply for retail, foodservice, manufacturing, and institutional channels.",
    descriptionFa:
      "تامین شکر برای فروشگاه‌ها، خدمات غذایی، تولیدکنندگان و کانال‌های سازمانی.",
    packagingOptionsEn: ["10kg bags", "25kg bags", "50kg bags"],
    packagingOptionsFa: ["کیسه ۱۰ کیلوگرمی", "کیسه ۲۵ کیلوگرمی", "کیسه ۵۰ کیلوگرمی"],
    certifications: sharedCertifications,
    shelfLifeEn: "24 months in dry storage",
    shelfLifeFa: "۲۴ ماه در انبار خشک",
    minOrderEn: "B2B inquiry",
    minOrderFa: "استعلام B2B",
    image: "/featured5.jpg",
    images: ["/featured5.jpg", "/featured1.jpg", "/featured2.jpg"],
    priceRangeEn: "Quote on request",
    priceRangeFa: "قیمت بر اساس استعلام",
    available: true,
  },
];
